language: python
python:
    - "3.4"
    - "3.5"
addons:
    - postgresql: '9.3'
install:
    - pip install -r requirements.txt
before_script:
    - pip install pep8
    - psql -c 'CREATE DATABASE typeyou;' -U postgres
    - make migrate
script:
    - pep8 .
notifications:
  slack: typeyou:cW32fYeMa22eSncpJoTgB364
  email: False
