language: python
python:
    - "3.4"
    - "3.5"
install:
    - pip install -r requirements.txt
before_script:
    - pip install pep8
script:
    - pep8 .
notifications:
  slack: typeyou:cW32fYeMa22eSncpJoTgB364
